FROM golang:1.10-stretch

ENV IPFS_VERSION 0.4.15

RUN wget https://dist.ipfs.io/go-ipfs/v${IPFS_VERSION}/go-ipfs_v${IPFS_VERSION}_linux-amd64.tar.gz

RUN tar -xvzf go-ipfs_v${IPFS_VERSION}_linux-amd64.tar.gz

ENV IPFS_PATH /data/ipfs

RUN mkdir -p ${IPFS_PATH}

VOLUME ${IPFS_PATH}

RUN cd go-ipfs && ./install.sh

RUN ipfs init

EXPOSE 4001
EXPOSE 5001
EXPOSE 8080
EXPOSE 8081

CMD ["ipfs","daemon","--init"]